### ISSUE TITLE
Colour filled - event 

### ISSUE THREAD

**Issue by ghost** [ebarellar/LFColoringBook#11]
![Simulator Screen Shot - iPhone 11 - 2022-01-01 at 02 27 15](https://user-images.githubusercontent.com/76158179/147838819-1e75f1ab-7c9c-400a-89f2-0c9287a6b166.png)

I stuck in one issue that, when I finish colouring in my art after that I want to display popup like painting has been completed so can you please let me know that by using which method or condition I can easily get callback when I finish colouring in design.

Thanks in advance.

**Comment by ebarellar** [comment]
You can probably do that whenever the delegate?.viewDidEndDrawing() method is called and then apply some logic to check if the drawing is "complete"

My guess is that you could check which mask was being processed, read the pixels from that region and check if all have alpha > 0. Then keep track on which masks are "full" and send the warning once all are done. I hope the performance hit isn't that bad
